In [1]:
# SuperVised Learning
# Unsupervised Learning

# Feature Information
# Target Information

# Classification (The output is discrete in nature.)
# Regression  (The predicted output is continuous in nature.)

# Unsupervised Learning we try to find relationship among the data. 
# Clustering and Dimensionality Reduction.

#### Scikit Learn (Machine Learning Library)

* Provides large number of common algorithms 

In [5]:
#### Data Representation in Scikit-Learn.
import seaborn as sns
iris = sns.load_dataset('iris')

In [6]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
iris.shape

(150, 5)

In [8]:
### Supervised Learning Example : Simple Liner Regresssion.
import matplotlib as plt
%matplotlib inline
import numpy as np

In [9]:
rng = np.random.RandomState(1)
x = 10 * rng.rand(50)

In [25]:
x
x.shape
x

array([  4.17022005e+00,   7.20324493e+00,   1.14374817e-03,
         3.02332573e+00,   1.46755891e+00,   9.23385948e-01,
         1.86260211e+00,   3.45560727e+00,   3.96767474e+00,
         5.38816734e+00,   4.19194514e+00,   6.85219500e+00,
         2.04452250e+00,   8.78117436e+00,   2.73875932e-01,
         6.70467510e+00,   4.17304802e+00,   5.58689828e+00,
         1.40386939e+00,   1.98101489e+00,   8.00744569e+00,
         9.68261576e+00,   3.13424178e+00,   6.92322616e+00,
         8.76389152e+00,   8.94606664e+00,   8.50442114e-01,
         3.90547832e-01,   1.69830420e+00,   8.78142503e+00,
         9.83468338e-01,   4.21107625e+00,   9.57889530e+00,
         5.33165285e+00,   6.91877114e+00,   3.15515631e+00,
         6.86500928e+00,   8.34625672e+00,   1.82882773e-01,
         7.50144315e+00,   9.88861089e+00,   7.48165654e+00,
         2.80443992e+00,   7.89279328e+00,   1.03226007e+00,
         4.47893526e+00,   9.08595503e+00,   2.93614148e+00,
         2.87775339e+00,

In [26]:
x.shape

(50,)

In [11]:
y = 2 * x + 1.5 

In [12]:
y

array([  9.84044009,  15.90648987,   1.5022875 ,   7.54665145,
         4.43511782,   3.3467719 ,   5.22520423,   8.41121454,
         9.43534948,  12.27633468,   9.88389029,  15.20439001,
         5.58904499,  19.06234873,   2.04775186,  14.9093502 ,
         9.84609605,  12.67379657,   4.30773877,   5.46202978,
        17.51489137,  20.86523151,   7.76848356,  15.34645231,
        19.02778305,  19.39213327,   3.20088423,   2.28109566,
         4.89660839,  19.06285007,   3.46693668,   9.9221525 ,
        20.6577906 ,  12.1633057 ,  15.33754228,   7.81031262,
        15.23001855,  18.19251344,   1.86576555,  16.5028863 ,
        21.27722178,  16.46331309,   7.10887984,  17.28558657,
         3.56452013,  10.45787052,  19.67191006,   7.37228297,
         7.25550677,   4.10057144])

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
model = LinearRegression(fit_intercept=True)

In [20]:
model
x[:,np.newaxis].shape

(50, 1)

In [17]:
# Train the Model with feature and target.
# Input data should be in form of list of rows.
model.fit(x[:,np.newaxis],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
model.coef_

array([ 2.])

In [22]:
model.intercept_

1.5000000000000053