In [2]:
# Model Validation
# Validating the Model is good enough or not.
# Parameters to create a Model is called Hyper Parameter

from sklearn.datasets import load_iris
iris = load_iris()
X=iris.data
y=iris.target

In [3]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:

# Model Creation

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
# model training
model.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

y_model = model.predict(X)

In [16]:
from sklearn.metrics import accuracy_score


In [17]:
### cross validation test on different data.

from sklearn.model_selection import train_test_split
X1,X2,y1,y2 = train_test_split(X,y,random_state=0, train_size=0.5)
# Divide Data into two parts, one part will be used for training and other for validation.

In [18]:
X1.shape


(75, 4)

In [19]:
X.shape

(150, 4)

In [20]:
X2.shape

(75, 4)

In [21]:
model.fit(X1,y1)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [22]:
y2_predict = model.predict(X2)
y2_model  = model.predict()

In [23]:
accuracy_score(y2,y2_model)

NameError: name 'y2_model' is not defined

In [26]:
from sklearn.cross_validation import cross_val_score

In [30]:
scores = cross_val_score(model,X,y,cv=5)

In [31]:
scores.mean()

0.95999999999999996

In [32]:
scores

array([ 0.96666667,  0.96666667,  0.93333333,  0.93333333,  1.        ])

# How to Select Best Model.
# How to really select a model.
# If the model is not working what do we do.
# Use a more complicated/flexible model
# Get More Training data.
# Get More data to add features to each sample

# Bias Variance Trade-off

* y = ax3 + bx2 + cx + d
* y = ax + b

In [34]:
#Create higher degree models

from sklearn.preprocessing import PolynomialFeatures

# Create Linear Regression Model
from sklearn.linear_model import LinearRegression

# Create Pipeline for finding the best model
from sklearn.pipeline import make_pipeline


In [35]:
# Function to create models
# kwargs contains hyper-parameters
# make_pipeline - Create pipeline of transformers & estimators
# Transformers will change data from one format to another such that they can be consumed by
# Estimators - model
# Transformers - PolynomialFeatures
# Estimators - LinearRegression


def PolynomialRegression(degree=2, **kwargs):
    return make_pipeline(PolynomialFeatures(degree),
                         LinearRegression(**kwargs))

In [ ]:
### Data Generation Function.
import numpy as np

def make_data(N, err=1.0, rseed=1):
    # randomly sample the data
    rng = np.random
