In [1]:
import numpy as np

In [2]:
a=np.zeros(10)

In [3]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
a[5]=1

In [5]:
a

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [6]:
s=[1,2,3,4,5,6,7,8,9,10]

In [7]:
np_a = np.array(s)

In [8]:
np_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np_a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np_a.reverse

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [11]:
np_a = np.reverse(s)

AttributeError: module 'numpy' has no attribute 'reverse'

In [12]:
np_a[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np_a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
h=np_a[::-1]

In [15]:
h


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
a=np.array(3,3,range(0,8))

ValueError: only 2 non-keyword arguments accepted

In [17]:
a=np.array((3,3),range(0,8))

TypeError: data type not understood

In [20]:
a=np.arange(0,8)

In [21]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])